services:
  - type: web
    name: monthsary
    env: node
    buildCommand: npm install -g serve
    startCommand: serve -s . -l 8080
    headers:
      - source: /
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
