services:
  - type: web
    name: monthsary
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: .
    headers:
      - source: /
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
